### PR TITLE
framework/web: add handler as part of request

### PR DESCRIPTION
**Pull request by Ompluscator**
This code adds handler name attribute to web.Request and so possibility to have information if there is assigned handler and it's name later in ChainFilter, Middleware or Controller.

### CODE REVIEW

**Comment by tessig** [comment]
Does it make sense to have the whole handler instead of only the name?

**Comment by Ompluscator** [comment]
> Does it make sense to have the whole handler instead of only the name?

Hi :)

I thought about it, but I could not find actual use case for that. In general, I can add that as well, but mostly I wanted to have option to know if handler is already found for request, when request is checked in Filter or Middleware.

So, would it be better to add that option as well?

**Comment by bastianccm** [comment]
Hey @Ompluscator I think it's better to just provide the whole Handler struct, not just the name. Then whoever needs something can pick whatever they like.

**Comment by Ompluscator** [comment]
> Hey @Ompluscator I think it's better to just provide the whole Handler struct, not just the name. Then whoever needs something can pick whatever they like.

Hi Mr Basti. Short question: would it be prefered to expose fields of Handler struct (as they are now private) and if so, which of them? If not, maybe to deliver new specific struct, which would expose some fields?

**Comment by bastianccm** [comment]
Hi Mr @Ompluscator, sorry for being late, the Handler struct should have getters for all fields, right?
https://github.com/i-love-flamingo/flamingo/blob/master/framework/web/registry.go#L507
I would go with that for the time being

**Comment by Ompluscator** [comment]
> Hi Mr @Ompluscator, sorry for being late, the Handler struct should have getters for all fields, right?
> https://github.com/i-love-flamingo/flamingo/blob/master/framework/web/registry.go#L507
> I would go with that for the time being

Ah true - thx! Then, I'll attach Handler object to response :)

**Review by bastianccm — APPROVED** [review]

**Pull request merged**
