### PR TITLE
chore: bump go version to 1.17, replace golint with staticcheck

### PR DESCRIPTION
**Pull request by bastianccm**
This is for testing coverage reports

* [x] This requires go 1.17 for running modules

### CODE REVIEW

**Comment by carstendietrich** [comment]
@bastianccm looks like a nice addition, feel free to bump go version to 1.17 and enable the optional static check checks. And of course please fix the newly raised issues 🙃

**Comment by carstendietrich** [comment]
Updated go version to 1.17, and fixed the staticcheck-raised issues.
The switch of the LogKey constants from type `string` to type `LogKey` is a breaking change.

**Comment by carstendietrich** [comment]
Moved coverage report to separate job, otherwise, we have two comments, one per go version (1.17/1.18)

**Comment by bastianccm** [comment]
LGTM, but i can't approve my own PR

**Review by carstendietrich — APPROVED** [review]

**Review by tessig — APPROVED** [review]

**Pull request merged**
