### PR TITLE
Version endpoint

### PR DESCRIPTION
**Pull request by danielpoe**
Some projects want build time informations returned by a path.

Typically this is done by writing a version.json file during build time.

This Feature provides an endpoint to return the content of that file, if given.

### CODE REVIEW

**Comment by thebod** [comment]
We should check "go build -X..." To set version info during compilation time.

**Comment by panzerfahrer** [comment]
Is this really worth putting into the framework? Feels slightly like the start of _eierlegendewollmilchsau_, doesn't it?

**Comment by danielpoe** [comment]
> We should check "go build -X..." To set version info during compilation time.

I like this idea.

Not sure about "eierlegendewollmilchsau" - one the one hand yes - on the other a quite common and simple use case and the code does not add complexity

**Comment by panzerfahrer** [comment]
This looks just like quite an opinionated solution and in the context of "some projects want" I'm not sure if this really adds value to the framework.

Hooking into the `SystemServer` is basically a 5-liner. And if that's quick enough to do, framework users can just add what ever they want (version numbers, git sha, timestamps, ...).

So I'd suggest to rather add method that allows to extend the behavior of the `SystemServer`.

**Comment by danielpoe** [comment]
> This looks just like quite an opinionated solution and in the context of "some projects want" I'm not sure if this really adds value to the framework.
> 
> Hooking into the `SystemServer` is basically a 5-liner. And if that's quick enough to do, framework users can just add what ever they want (version numbers, git sha, timestamps, ...).
> 
> So I'd suggest to rather add method that allows to extend the behavior of the `SystemServer`.

by returning the content of a variable "BUILDINFO" or whatever it returns what everyone wants to be returned.
I still dont see that this feature is a super project specific thing but rather something generic

**Comment by bastianccm** [comment]
Alternative proposal in #156

**Comment by bastianccm** [comment]
For now superseded by #156

**Pull request closed without merging**
